[package]
name = "utils-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.6"
reqwest = "0.11.24"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
